#!/usr/bin/env node
// Native API errors use the same catalog as Web. Parse literals with the
// TypeScript AST; do not execute locale modules or duplicate translations.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const root = new URL('../../../', import.meta.url);
const require = createRequire(new URL('apps/gooseforum/resource/package.json', root));
const ts = require('typescript');
const target = new URL('apps/mobile/packages/forum_app/lib/src/server_message_catalog.dart', root);

function literal(node) {
  if (ts.isStringLiteralLike(node)) return node.text;
  if (!ts.isObjectLiteralExpression(node)) throw new Error('Expected a locale object or string');
  return Object.fromEntries(node.properties.map((property) => {
    if (!ts.isPropertyAssignment(property) || !('text' in property.name)) {
      throw new Error('Locale catalogs must contain literal properties');
    }
    return [property.name.text, literal(property.initializer)];
  }));
}

function flatten(object, prefix = '') {
  return Object.fromEntries(Object.entries(object).flatMap(([key, value]) => {
    const path = prefix ? `${prefix}.${key}` : key;
    return typeof value === 'string' ? [[path, value]] : Object.entries(flatten(value, path));
  }));
}

const dartString = (value) => JSON.stringify(value).replaceAll('$', '\\$');
let output = '// Generated by apps/mobile/tools/generate_server_messages.mjs. Do not edit.\n'
  + '// Source: apps/gooseforum/resource/src/locales/{zh,en,ja,de}.ts\n'
  + '// dart format off\n'
  + 'const Map<String, Map<String, String>> serverMessageCatalog = {\n';
let count = 0;
for (const locale of ['zh', 'en', 'ja', 'de']) {
  const path = new URL(`apps/gooseforum/resource/src/locales/${locale}.ts`, root);
  const source = ts.createSourceFile(fileURLToPath(path), readFileSync(path, 'utf8'), ts.ScriptTarget.Latest, true);
  const exported = source.statements.find(ts.isExportAssignment)?.expression;
  if (!exported || !ts.isObjectLiteralExpression(exported)) throw new Error('Missing locale export');
  const catalogs = {};
  for (const property of exported.properties) {
    if (ts.isPropertyAssignment(property) && ['server', 'serverMessages'].includes(property.name.text)) {
      catalogs[property.name.text] = literal(property.initializer);
    }
  }
  const merged = { ...flatten(catalogs.server), ...catalogs.serverMessages };
  output += `  ${dartString(locale)}: {\n`;
  for (const [key, value] of Object.entries(merged).sort(([a], [b]) => a.localeCompare(b, 'en'))) {
    output += `    ${dartString(key)}: ${dartString(value)},\n`;
    count++;
  }
  output += '  },\n';
}
output += '};\n// dart format on\n';
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== output) {
    throw new Error('Mobile messages are stale; run node apps/mobile/tools/generate_server_messages.mjs');
  }
} else {
  writeFileSync(target, output);
}
console.log(`Mobile server messages: ${count} translations synchronized.`);
