// The API currently identifies fixed fields with Chinese labels. Translate only
// their presentation; retain original identifiers and all upstream record values.
const fieldKeys: Record<string, string> = {
  '姓名': 'campus.fieldName',
  '当前学期': 'campus.fieldCurrentTerm',
  '教学周': 'campus.fieldTeachingWeek',
  '学期周数': 'campus.fieldTermWeeks',
  '学期开始': 'campus.fieldTermStart',
  '学期结束': 'campus.fieldTermEnd',
  '课程': 'campus.fieldCourse',
  '教师': 'campus.fieldTeacher',
  '学分': 'campus.fieldCredits',
  '校区': 'campus.fieldCampus',
  '上课安排': 'campus.fieldSchedule',
  '本学期课程': 'campus.fieldTermCourses',
  '累计绩点': 'campus.fieldGradePoints',
  '已获学分': 'campus.fieldEarnedCredits',
  '未通过课程': 'campus.fieldFailedCourses',
  '学期': 'campus.fieldTerm',
  '成绩': 'campus.fieldScore',
  '绩点': 'campus.fieldGpa',
  '考试性质': 'campus.fieldExamType',
  '综合 GPA': 'campus.fieldOverallGpa',
  '百分制均分': 'campus.fieldAverage',
  '已修学分': 'campus.fieldCompletedCredits',
  '要求学分': 'campus.fieldRequiredCredits',
  '考试学期': 'campus.fieldExamTerm',
  '考试科目': 'campus.fieldExamSubject',
  '笔试成绩': 'campus.fieldWrittenScore',
  '口试成绩': 'campus.fieldOralScore',
  '开始日期': 'campus.fieldStartDate',
  '结束日期': 'campus.fieldEndDate',
  '周数': 'campus.fieldWeeks',
  '标题': 'campus.fieldTitle',
  '发布单位': 'campus.fieldPublisher',
  '发布时间': 'campus.fieldPublishedAt',
  '消息总数': 'campus.fieldMessageCount',
  '周': 'campus.unitWeeks',
  '门': 'campus.unitCourses',
  '条': 'campus.unitMessages',
}
export function campusFieldKey(label: string): string | undefined {
  return Object.hasOwn(fieldKeys, label) ? fieldKeys[label] : undefined
}
